# Generated by Django 5.2.2 on 2025-07-06 16:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cod_producto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='venta',
            name='fec_venta',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('cod_venta_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.producto')),
                ('cod_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='venta.venta')),
            ],
        ),
    ]
